import Head from "next/head";
import Landing from "../components/Landing/Landing";
import Overview from "../components/Overview/Overview";
import Reviews from "../components/Reviews/Reviews";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Développement de Site Web et Média Photo et vidéo | ComPote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Landing />
        <Overview />
        <Reviews />
      </div>
    </>
  );
}
