import Head from "next/head";
import Slider from "../components/Slider/Slider";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Développement de Site Web et Média Photo et vidéo | ComPote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Slider />
        <main>
          <h1>ComPote</h1>
          <h2>Votre acolyte dans tous vos projets</h2>
        </main>
      </div>
    </>
  );
}
